# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class MarketStatus(StrEnum):
    OPEN = 'OPEN'
    PENDING_RESOLUTION = 'PENDING_RESOLUTION'
    RESOLVED = 'RESOLVED'
    INVALID = 'INVALID'
    PAUSED = 'PAUSED'

class Outcome(StrEnum):
    UNRESOLVED = 'UNRESOLVED'
    YES = 'YES'
    NO = 'NO'
    INVALID = 'INVALID'

class ResolutionType(StrEnum):
    GITHUB_PR = 'GITHUB_PR'
    GITHUB_RELEASE = 'GITHUB_RELEASE'
    GITHUB_ISSUE = 'GITHUB_ISSUE'
    CI_METRIC = 'CI_METRIC'
    CVE_SECURITY = 'CVE_SECURITY'
    WEB3_RPC = 'WEB3_RPC'
    DAO_GOVERNANCE = 'DAO_GOVERNANCE'
    LLM_JUDGE = 'LLM_JUDGE'

